% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={CR\_Portfolio\_2},
  pdfauthor={Seunghun Lee},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{CR\_Portfolio\_2}
\author{Seunghun Lee}
\date{Oct 12, 2020}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{research-question}{%
\subsection{Research Question}\label{research-question}}

Researchers were interested in whether the correlation between first
mathematics exam score (G1) and final mathematics exam score (G3) was
stronger for male students than female students in a secondary education
of Portuguese school. They obtained a random sample of 395 students (208
females, 187 males) from an independent dataset and investigated their
research question using an alpha of 0.05 (P. Cortez and A. Silva, 2008).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# https://archive.ics.uci.edu/ml/datasets/student+performance}
\NormalTok{dat <-}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\StringTok{'./data/student-mat.csv'}\NormalTok{,}\DataTypeTok{sep=}\StringTok{";"}\NormalTok{,}\DataTypeTok{header=}\OtherTok{TRUE}\NormalTok{)}
\CommentTok{# Subset necessary attributes}
\NormalTok{dat_f <-}\StringTok{ }\NormalTok{dat }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(sex, G1, G3) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(sex }\OperatorTok{==}\StringTok{ 'F'}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(dat_f)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  sex           G1              G3        
##  F:208   Min.   : 4.00   Min.   : 0.000  
##  M:  0   1st Qu.: 8.00   1st Qu.: 8.000  
##          Median :10.00   Median :10.000  
##          Mean   :10.62   Mean   : 9.966  
##          3rd Qu.:13.00   3rd Qu.:13.000  
##          Max.   :19.00   Max.   :19.000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat_m <-}\StringTok{ }\NormalTok{dat }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(sex, G1, G3) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(sex  }\OperatorTok{==}\StringTok{ 'M'}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(dat_m)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  sex           G1              G3       
##  F:  0   Min.   : 3.00   Min.   : 0.00  
##  M:187   1st Qu.: 9.00   1st Qu.: 9.00  
##          Median :11.00   Median :11.00  
##          Mean   :11.23   Mean   :10.91  
##          3rd Qu.:14.00   3rd Qu.:14.00  
##          Max.   :19.00   Max.   :20.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(sex, G1, G3) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(G1, G3, }\DataTypeTok{color =}\NormalTok{ sex)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{'lm'}\NormalTok{, }\DataTypeTok{se =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_grid}\NormalTok{(}\DataTypeTok{cols =} \KeywordTok{vars}\NormalTok{(sex)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{'First Exam Score (G1) vs Final Exam Score (G3)'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"none"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{CR_Portfolio_2_files/figure-latex/unnamed-chunk-2-1.pdf}

\hypertarget{hypotheses}{%
\subsection{Hypotheses}\label{hypotheses}}

\(H_{1}\): The correlation between first exam score (G1) and final exam
score (G3) was stronger for male than female
(\(\rho_{M} - \rho_{F} > 0\))\\
\(H_{0}\): The correlation between first exam score (G1) and final score
(G3) was not stronger for male than female
(\(\rho_{M} - \rho_{F} \le 0\))\\

\hypertarget{critical-test-statistic}{%
\subsection{Critical test statistic}\label{critical-test-statistic}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{round}\NormalTok{(}\KeywordTok{abs}\NormalTok{(}\KeywordTok{qnorm}\NormalTok{(}\FloatTok{0.05}\NormalTok{)), }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.645
\end{verbatim}

\(\alpha\) = 0.05, one-tailed, Critical Z-statistics = 1.645

\hypertarget{test-statistic}{%
\subsection{Test statistic}\label{test-statistic}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Build a function for independent correlation test

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{indep_cor_test <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(data, group, var1, var2)\{}
  \CommentTok{#Get group levels}
\NormalTok{  group_levels <-}\StringTok{ }\NormalTok{data }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{pull}\NormalTok{(\{\{group\}\}) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{levels}\NormalTok{()}
  \CommentTok{#Correlation in group 1}
\NormalTok{  data1 <-}\StringTok{ }\NormalTok{data }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{select}\NormalTok{(\{\{group\}\}, \{\{var1\}\}, \{\{var2\}\}) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{filter}\NormalTok{(\{\{group\}\} }\OperatorTok{==}\StringTok{ }\NormalTok{group_levels[}\DecValTok{1}\NormalTok{]) }
\NormalTok{  cor1 <-}\StringTok{ }\NormalTok{data1 }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{var1 =}\NormalTok{ var1 <-}\StringTok{ }\NormalTok{\{\{var1\}\},}
           \DataTypeTok{var2 =}\NormalTok{ var2 <-}\StringTok{ }\NormalTok{\{\{var2\}\}) }\OperatorTok{%$%}
\StringTok{    }\KeywordTok{cor}\NormalTok{(var1, var2)}
  \CommentTok{#Correlation in group 2}
\NormalTok{  data2 <-}\StringTok{ }\NormalTok{data }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{select}\NormalTok{(\{\{group\}\}, \{\{var1\}\}, \{\{var2\}\}) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{filter}\NormalTok{(\{\{group\}\} }\OperatorTok{==}\StringTok{ }\NormalTok{group_levels[}\DecValTok{2}\NormalTok{])}
\NormalTok{  cor2 <-}\StringTok{ }\NormalTok{data2 }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{var1 =}\NormalTok{ var1 <-}\StringTok{ }\NormalTok{\{\{var1\}\},}
           \DataTypeTok{var2 =}\NormalTok{ var2 <-}\StringTok{ }\NormalTok{\{\{var2\}\}) }\OperatorTok{%$%}
\StringTok{    }\KeywordTok{cor}\NormalTok{(var1, var2)}
  \CommentTok{#Independent correlation test}
\NormalTok{  rtest <-}\StringTok{ }\KeywordTok{r.test}\NormalTok{(}\DataTypeTok{n =} \KeywordTok{nrow}\NormalTok{(data1), }\DataTypeTok{n2 =} \KeywordTok{nrow}\NormalTok{(data2), cor1, cor2, }\DataTypeTok{twotailed =} \OtherTok{FALSE}\NormalTok{)}
  \CommentTok{#print the results}
  \KeywordTok{print}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"The correlation in"}\NormalTok{, group_levels[}\DecValTok{1}\NormalTok{]))}
  \KeywordTok{print}\NormalTok{(cor1)}
  \KeywordTok{print}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"The correlation in"}\NormalTok{, group_levels[}\DecValTok{2}\NormalTok{]))}
  \KeywordTok{print}\NormalTok{(cor2)}
\NormalTok{  rtest}
\NormalTok{  \}}
\end{Highlighting}
\end{Shaded}
\end{enumerate}

\begin{itemize}
\item
  Computation by the function above

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{indep_cor_test}\NormalTok{(dat, sex, G1, G3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "The correlation in F"
## [1] 0.7721856
## [1] "The correlation in M"
## [1] 0.8307415
\end{verbatim}

\begin{verbatim}
## Correlation tests 
## Call:r.test(n = nrow(data1), r12 = cor1, r34 = cor2, n2 = nrow(data2), 
##     twotailed = FALSE)
## Test of difference between two independent correlations 
##  z value 1.62    with probability  0.05
\end{verbatim}
\item
  Result sample statistic Z value 1.62 \textless{} Critical Z-statistic
  1.645\\
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\item
  Computation by hand

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{manual_z <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(n1, cor1, n2, cor2)\{}
\NormalTok{  z1 <-}\StringTok{ }\FloatTok{0.5}\OperatorTok{*}\KeywordTok{log}\NormalTok{((}\DecValTok{1}\OperatorTok{+}\NormalTok{cor1)}\OperatorTok{/}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{cor1))}
\NormalTok{  z2 <-}\StringTok{ }\FloatTok{0.5}\OperatorTok{*}\KeywordTok{log}\NormalTok{((}\DecValTok{1}\OperatorTok{+}\NormalTok{cor2)}\OperatorTok{/}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{cor2))}

\NormalTok{  z <-}\StringTok{ }\NormalTok{((z2 }\OperatorTok{-}\StringTok{ }\NormalTok{z1) }\OperatorTok{-}\StringTok{ }\DecValTok{0}\NormalTok{)}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{((}\DecValTok{1}\OperatorTok{/}\NormalTok{(n1}\DecValTok{-3}\NormalTok{))}\OperatorTok{+}\NormalTok{(}\DecValTok{1}\OperatorTok{/}\NormalTok{(n2}\DecValTok{-3}\NormalTok{)))}
  \KeywordTok{print}\NormalTok{(}\KeywordTok{abs}\NormalTok{(z))}
\NormalTok{\}}

\KeywordTok{manual_z}\NormalTok{(}\DecValTok{208}\NormalTok{, }\FloatTok{0.7721856}\NormalTok{, }\DecValTok{187}\NormalTok{, }\FloatTok{0.8307415}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.622869
\end{verbatim}
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Result sample statistic Z value 1.623 \textless{} Critical Z-statistic
  1.645\\
\end{itemize}

\hypertarget{conclusion}{%
\subsection{Conclusion}\label{conclusion}}

\begin{itemize}
\tightlist
\item
  Fail to reject the null hypothesis\\
\item
  The correlation between G1 and G3 was not significantly stronger for
  male than for female\\
\item
  {[}\(r_{F}\) = 0.77, \(n_{F}\) = 208, \(r_{M}\) = 0.83, \(n_{M}\) =
  187, Z = 1.62, p \textgreater{} 0.05{]}
\end{itemize}

\end{document}
